# Generated by Django 5.0.6 on 2024-06-17 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='guest',
            new_name='guests',
        ),
    ]
